flags: {}
packages:
- '.'
- '../approximate'
- '../hyperloglog'
extra-deps:
    [ gamma-0.9.0.2
    , continued-fractions-0.9.1.1
    , converge-0.1.0.1
    , bloomfilter-2.0.1.0
    ]
resolver: nightly-2016-08-30
